name: CI

on:
  pull_request:
    paths:
      - '**.gd'
      - '!addons/**'
  push:
    branches: [ main ]
    paths:
      - '**.gd'
      - '!addons/**'
  workflow_dispatch:

jobs:
  lint:
    name: 'Lint GDScript'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup gdtoolkit
      uses: Scony/godot-gdscript-toolkit@master

    - name: Run GDLint
      run: find . -name '*.gd' -and ! -path './addons/*' | xargs gdlint
  
  format:
    name: 'Check Format GDScript'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup gdtoolkit
      uses: Scony/godot-gdscript-toolkit@master

    - name: Check formatting
      run: find . -name '*.gd' -and ! -path './addons/*' | xargs gdformat --check
      
  tests:
    name: 'Run Unit Tests'
    runs-on: ubuntu-latest
    container: 
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Godot
        run: godot --headless --import
        
      - name: Run GUT
        run: godot -d -s --path "$PWD" addons/gut/gut_cmdln.gd -gdir=res://tests/unit -gpreffix=test_ -gsuffix=.gd -gexit
